apiVersion: v1
items:
- apiVersion: certificates.k8s.io/v1
  kind: CertificateSigningRequest
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"certificates.k8s.io/v1","kind":"CertificateSigningRequest","metadata":{"annotations":{},"name":"adam"},"spec":{"expirationSeconds":25600000,"request":"LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0NCk1JSUNWRENDQVR3Q0FRQXdEekVOTUFzR0ExVUVBd3dFWVdSaGJUQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQUQNCmdnRVBBRENDQVFvQ2dnRUJBTjA3RkhtekR3aGo3Z085NVgybFF5bS96UjR5anYvSGxKTGR0cndtOU1XNU1OK0ENClV4VkV2eEcvZlEreDVTaGlWcjFBZjZGa0xXQzVsZ09LK0hnL3FXVXQ2V1B2ZDhaTnN6V3hEVnZiYVNDODJEWkoNCnJHQU04bGVXVnBYRzgwUlUxb2g3OW1TdWluNERGRlhLUjlMQ2tEbHpHTUw4dW1oUG5wZnpZekljS1VibVIvR3ENCnZFWnVEV0FDQjVmckpCUVB6RmwzYS83NS9waklUOUxvb3VKbDVEYy9kQVErQVZwQ3BjbUNET1pnMDU4aHNjMFYNClFKd3dTRDdVM1d6bnpDOS9zOThCWnBSSThFUzFmY1hjc1p1YWlJN3ZiZ1ZNSmR5dXZPTktmNkg5MWlCWVdtcU4NCkhBZHI1RGFhaFl6VC9ON0JOaEZXQUgvZHIraXgxVDdicWhsL24xVUNBd0VBQWFBQU1BMEdDU3FHU0liM0RRRUINCkN3VUFBNElCQVFCOTJkNkJWc0I5NVRyNHR0MWhVYWJDMmp6d3I2Ykw3UmQycDlTSHo5bURQajlRVkVudUhiZGMNCmF2OEl5UjFhOUhZSm5JMThDQjhOQVhjQ2VJS0Jlcms5RDloQnJFTVZNMisvelR0Si92REJpSVAzSy9veE54M08NClliRDZsQ3BnWHE5WlJmTE5mc1ozcjV4U1FYaU9pSXJkOU93cThlWGVIQVRMQ05qVUp1Wk5XNXF1RWNLTVEwS0gNCmUwTGpaSThYUjRQcmE3a2lKc1JqNjdKdU95VExHUTJIcDA2ejA4MnNzM2F6azRzaWppZ0lOV2NwUHB2QkdTM0YNCk9venVNNlJEMVJPa1RZN0k1UXFPZkZHNFFjYi9uMDZVRFllaW9pOWlZU1RhQ2JKNGltMGkzZGwyWFhteENQUG8NCmV1V3RqS2xWOHRuSWJnQnNGYkxKZ2Z4bGI1YXVmamhKDQotLS0tLUVORCBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0NCg==","signerName":"kubernetes.io/kube-apiserver-client","usages":["client auth"]}}
    creationTimestamp: "2026-08-07T12:23:42Z"
    name: adam
    resourceVersion: "6524"
    uid: 0fb6d471-71b8-43bd-9d31-af0848c18e51
  spec:
    expirationSeconds: 25600000
    extra:
      authentication.kubernetes.io/credential-id:
      - X509SHA256=062deeb48aad5352c61e02f20e3b0c207a481584f90f0fd80f16253313261e1b
    groups:
    - kubeadm:cluster-admins
    - system:authenticated
    request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0NCk1JSUNWRENDQVR3Q0FRQXdEekVOTUFzR0ExVUVBd3dFWVdSaGJUQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQUQNCmdnRVBBRENDQVFvQ2dnRUJBTjA3RkhtekR3aGo3Z085NVgybFF5bS96UjR5anYvSGxKTGR0cndtOU1XNU1OK0ENClV4VkV2eEcvZlEreDVTaGlWcjFBZjZGa0xXQzVsZ09LK0hnL3FXVXQ2V1B2ZDhaTnN6V3hEVnZiYVNDODJEWkoNCnJHQU04bGVXVnBYRzgwUlUxb2g3OW1TdWluNERGRlhLUjlMQ2tEbHpHTUw4dW1oUG5wZnpZekljS1VibVIvR3ENCnZFWnVEV0FDQjVmckpCUVB6RmwzYS83NS9waklUOUxvb3VKbDVEYy9kQVErQVZwQ3BjbUNET1pnMDU4aHNjMFYNClFKd3dTRDdVM1d6bnpDOS9zOThCWnBSSThFUzFmY1hjc1p1YWlJN3ZiZ1ZNSmR5dXZPTktmNkg5MWlCWVdtcU4NCkhBZHI1RGFhaFl6VC9ON0JOaEZXQUgvZHIraXgxVDdicWhsL24xVUNBd0VBQWFBQU1BMEdDU3FHU0liM0RRRUINCkN3VUFBNElCQVFCOTJkNkJWc0I5NVRyNHR0MWhVYWJDMmp6d3I2Ykw3UmQycDlTSHo5bURQajlRVkVudUhiZGMNCmF2OEl5UjFhOUhZSm5JMThDQjhOQVhjQ2VJS0Jlcms5RDloQnJFTVZNMisvelR0Si92REJpSVAzSy9veE54M08NClliRDZsQ3BnWHE5WlJmTE5mc1ozcjV4U1FYaU9pSXJkOU93cThlWGVIQVRMQ05qVUp1Wk5XNXF1RWNLTVEwS0gNCmUwTGpaSThYUjRQcmE3a2lKc1JqNjdKdU95VExHUTJIcDA2ejA4MnNzM2F6azRzaWppZ0lOV2NwUHB2QkdTM0YNCk9venVNNlJEMVJPa1RZN0k1UXFPZkZHNFFjYi9uMDZVRFllaW9pOWlZU1RhQ2JKNGltMGkzZGwyWFhteENQUG8NCmV1V3RqS2xWOHRuSWJnQnNGYkxKZ2Z4bGI1YXVmamhKDQotLS0tLUVORCBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0NCg==
    signerName: kubernetes.io/kube-apiserver-client
    usages:
    - client auth
    username: kubernetes-admin
  status:
    certificate: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM5VENDQWQyZ0F3SUJBZ0lSQU92djB3TDBjdUxoNzZQR2NLdHdPNTh3RFFZSktvWklodmNOQVFFTEJRQXcKRlRFVE1CRUdBMVVFQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TmpBNE1EY3hNakl3TXpCYUZ3MHlOekExTXpBeApPVEkzTVRCYU1BOHhEVEFMQmdOVkJBTVRCR0ZrWVcwd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUJEd0F3CmdnRUtBb0lCQVFEZE94UjVzdzhJWSs0RHZlVjlwVU1wdjgwZU1vNy94NVNTM2JhOEp2VEZ1VERmZ0ZNVlJMOFIKdjMwUHNlVW9ZbGE5UUgraFpDMWd1WllEaXZoNFA2bGxMZWxqNzNmR1RiTTFzUTFiMjJrZ3ZOZzJTYXhnRFBKWApsbGFWeHZORVZOYUllL1prcm9wK0F4UlZ5a2ZTd3BBNWN4akMvTHBvVDU2WDgyTXlIQ2xHNWtmeHFyeEdiZzFnCkFnZVg2eVFVRDh4WmQydisrZjZZeUUvUzZLTGlaZVEzUDNRRVBnRmFRcVhKZ2d6bVlOT2ZJYkhORlVDY01FZysKMU4xczU4d3ZmN1BmQVdhVVNQQkV0WDNGM0xHYm1vaU83MjRGVENYY3JyempTbitoL2RZZ1dGcHFqUndIYStRMgptb1dNMC96ZXdUWVJWZ0IvM2Evb3NkVSsyNm9aZjU5VkFnTUJBQUdqUmpCRU1CTUdBMVVkSlFRTU1Bb0dDQ3NHCkFRVUZCd01DTUF3R0ExVWRFd0VCL3dRQ01BQXdId1lEVlIwakJCZ3dGb0FVTG5kQnZodEttN2xYdkw3Z3ZSSS8KRkxYQlExb3dEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBS1JJRUo5a0VydlJ3L2M1N3hLYkFlRkdBNkxtU3Z5RwpiQ05sdW5WZi9sbXJEUTJyWGhWcnNldGZZalF2VjhVYVM3ang2UkRrZGxxcEozdUJqTDQ0MHdETFFEc2VOSVhuCm50UXViSlNpNEhIV1pHdyszSzVlMWNzUFdUQzI5dFQ2VlhFZUpYL2JRU2dvMFBkaENKQ3NoVlFsNVRMRitvcmUKUHJZMjdwcWdUdHhzamY3anJFSHlUVi9ibSs0TVM5azUvTFUyVmVkM0k0QlprTGJyb0lGV1BNcFpaekpya0dBRwpxTkRZdk5MVW5QRkZUbmtCdGNQQnR2ZDcxRzZ2Y0RPeXVNcUc1SThoRHVnMlVxd3R2WkxpQUR3Z0pseXZORHVFCld4cVgvZ21zRVFyekhXK0dWQWdSMEdHQ1dFd2tydzZhMStpdm1hSHBQWW5DeWJSdm1Za0hMbk09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    conditions:
    - lastTransitionTime: "2026-08-07T12:25:30Z"
      lastUpdateTime: "2026-08-07T12:25:30Z"
      message: This CSR was approved by kubectl certificate approve.
      reason: KubectlApprove
      status: "True"
      type: Approved
- apiVersion: certificates.k8s.io/v1
  kind: CertificateSigningRequest
  metadata:
    creationTimestamp: "2026-08-07T11:19:29Z"
    generateName: csr-
    name: csr-9h85v
    resourceVersion: "386"
    uid: 1cdf8105-819c-4697-948a-90949e20d81c
  spec:
    groups:
    - system:bootstrappers
    - system:bootstrappers:kubeadm:default-node-token
    - system:authenticated
    request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlIME1JR2JBZ0VBTURreEZUQVRCZ05WQkFvVERITjVjM1JsYlRwdWIyUmxjekVnTUI0R0ExVUVBeE1YYzNsegpkR1Z0T201dlpHVTZiV0ZwYmkxM2IzSnJaWEl3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkNBQVFkCitaVTdXWFJ5VHFjZldDd2k1YngxWTFWWEVkUmQ0TWdlS2ZiSjFaZ2FodWZVUkl2Q3BlOWJmQ3hTRkh3OER6RmIKR0NMeFZZb1UvbzJrUFRaZG9TZXNvQUF3Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUloQU15bVhOZEFBMHFkZEtpbwphUWwrNHM2cDNDRnVIU0xsMElKSUVsZlN6YzN0QWlCNUoyQk4yNXNVd1A0ZjdZNGI2YnM1bngzdmdQZlR1bFRjCkxuZnduZCszNlE9PQotLS0tLUVORCBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0K
    signerName: kubernetes.io/kube-apiserver-client-kubelet
    usages:
    - digital signature
    - client auth
    username: system:bootstrap:abcdef
  status:
    certificate: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNZekNDQVV1Z0F3SUJBZ0lRYWFrTFdTdUxCTHB5Y0k5NkxpaXlvVEFOQmdrcWhraUc5dzBCQVFzRkFEQVYKTVJNd0VRWURWUVFERXdwcmRXSmxjbTVsZEdWek1CNFhEVEkyTURnd056RXhNVFF5T1ZvWERUSTNNRGd3TnpFeApNVFF5T1Zvd09URVZNQk1HQTFVRUNoTU1jM2x6ZEdWdE9tNXZaR1Z6TVNBd0hnWURWUVFERXhkemVYTjBaVzA2CmJtOWtaVHB0WVdsdUxYZHZjbXRsY2pCWk1CTUdCeXFHU000OUFnRUdDQ3FHU000OUF3RUhBMElBQkIzNWxUdFoKZEhKT3B4OVlMQ0xsdkhWalZWY1IxRjNneUI0cDlzblZtQnFHNTlSRWk4S2w3MXQ4TEZJVWZEd1BNVnNZSXZGVgppaFQramFROU5sMmhKNnlqVmpCVU1BNEdBMVVkRHdFQi93UUVBd0lIZ0RBVEJnTlZIU1VFRERBS0JnZ3JCZ0VGCkJRY0RBakFNQmdOVkhSTUJBZjhFQWpBQU1COEdBMVVkSXdRWU1CYUFGQzUzUWI0YlNwdTVWN3krNEwwU1B4UzEKd1VOYU1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQVBOWEdmZFZERFc5VC9wNHpCZWtVMUFmTThEU2FSMllzRwpiMzJHMUt0cjEvdm8ybnRycUpLa3kybDhGR01xYVB0Zlc1c3VQdFpTSjFmNmFhWnhia0dySUVnRDh4SVFscHQvCmx1L1I0YzhkbTZhMXU1ZEFzZm9aOXJ1QXY5dUxvOHdIZVUwR0M2ay9SRWM3UEw5dm5JQW1RazJRSGdxK3I4VncKNUczK2d5SGNPeEYxbDVsZ2QrV0svbDVWbVlLcXJrZFNiTU9yMlVpYURiaEhGdDJMOWo3NWw0K1plNUdBdEhKSgpPVHdQY1U3ZjhzYTF5T21uM3NXT2NLNFExRUJMUVpGVUxldWdlbUJMeVloN0tKWUlPSVlMUnRLT1ZZalB1WHMvCmR4UzQrVHErbE5VaTVzbkE3YU9Zemc0SmQ5dzBoemx1YmtJakNhMURmdTU1djdJcWRXckQKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    conditions:
    - lastTransitionTime: "2026-08-07T11:19:29Z"
      lastUpdateTime: "2026-08-07T11:19:29Z"
      message: Auto approving kubelet client certificate after SubjectAccessReview.
      reason: AutoApproved
      status: "True"
      type: Approved
- apiVersion: certificates.k8s.io/v1
  kind: CertificateSigningRequest
  metadata:
    creationTimestamp: "2026-08-07T11:19:29Z"
    generateName: csr-
    name: csr-hk79z
    resourceVersion: "379"
    uid: 097d0604-4318-4a57-92cd-3d5f16935140
  spec:
    groups:
    - system:bootstrappers
    - system:bootstrappers:kubeadm:default-node-token
    - system:authenticated
    request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlIMU1JR2NBZ0VBTURveEZUQVRCZ05WQkFvVERITjVjM1JsYlRwdWIyUmxjekVoTUI4R0ExVUVBeE1ZYzNsegpkR1Z0T201dlpHVTZiV0ZwYmkxM2IzSnJaWEl5TUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFCjNaVC9kL2pWcGdkSDRZcnhXdFMxUTdVNmZFQkYzV0krTUo3VUkwckpFZEdtSGlDWEVOKzdscUJiVXFNZEY3b1AKNVlJcnA5SGYxb1dPcTZmeTVWamVvcUFBTUFvR0NDcUdTTTQ5QkFNQ0EwZ0FNRVVDSVFEeEM0ZzhLT0xpV2pqOQpzVSsvVXRPd01hblMrZFB3VnovMElXdUVpek0wbXdJZ1hteFI0OFJZUkFOaDNKdlM3QW9WZDFqSXJIT2tvME43Ck0wMGREaUlyNkg4PQotLS0tLUVORCBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0K
    signerName: kubernetes.io/kube-apiserver-client-kubelet
    usages:
    - digital signature
    - client auth
    username: system:bootstrap:abcdef
  status:
    certificate: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNaRENDQVV5Z0F3SUJBZ0lRSjFsdU1hZCtmQXZNRmVGZDZ2bWtSekFOQmdrcWhraUc5dzBCQVFzRkFEQVYKTVJNd0VRWURWUVFERXdwcmRXSmxjbTVsZEdWek1CNFhEVEkyTURnd056RXhNVFF5T1ZvWERUSTNNRGd3TnpFeApNVFF5T1Zvd09qRVZNQk1HQTFVRUNoTU1jM2x6ZEdWdE9tNXZaR1Z6TVNFd0h3WURWUVFERXhoemVYTjBaVzA2CmJtOWtaVHB0WVdsdUxYZHZjbXRsY2pJd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DQUFUZGxQOTMKK05XbUIwZmhpdkZhMUxWRHRUcDhRRVhkWWo0d250UWpTc2tSMGFZZUlKY1EzN3VXb0Z0U294MFh1Zy9sZ2l1bgowZC9XaFk2cnAvTGxXTjZpbzFZd1ZEQU9CZ05WSFE4QkFmOEVCQU1DQjRBd0V3WURWUjBsQkF3d0NnWUlLd1lCCkJRVUhBd0l3REFZRFZSMFRBUUgvQkFJd0FEQWZCZ05WSFNNRUdEQVdnQlF1ZDBHK0cwcWJ1VmU4dnVDOUVqOFUKdGNGRFdqQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFKSVc0N3NxNEFvL1N6bGswNFdBU0VFcllndWZBN3FMdQp0ZnlSbWtFamdVNytqSUZOQ0hnUTEvQW8zQkliSE16TmxPYklmWVludURvSnB4ejh6YVQwbXcwZnFmS2NGR1BBClozdHdFKy80MU5TUkVxbVVOa2N2eGM5NnR1Mkl4NGdpSVVvNXNyaDVqdmVoWjh0WmZ5eEQwb2MzV3JSRllWZ2EKL21ZUTZXcHVscWVyTFBsNm1HUnlkcVlyNUZUc3hVODZKZG9aNEZlTGRPZTJ4dEZUUEhxZmkwekp2b2E1VExoYQo1WTVHS3h6VURIM093WVNwbms4Y2JobjlMODg0ZjhlWWVKeVRjNk5hdkFtQTFNeDh2VEhEMmpyZG1zOTJpZU41CjczSHUzWEpaYkJRSXpUT05SUkFXeU5VY2hlTDZUZ2lMMW42UzBjcEhMdjRKVTRra1E4SHVsQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    conditions:
    - lastTransitionTime: "2026-08-07T11:19:29Z"
      lastUpdateTime: "2026-08-07T11:19:29Z"
      message: Auto approving kubelet client certificate after SubjectAccessReview.
      reason: AutoApproved
      status: "True"
      type: Approved
- apiVersion: certificates.k8s.io/v1
  kind: CertificateSigningRequest
  metadata:
    creationTimestamp: "2026-08-07T11:19:19Z"
    generateName: csr-
    name: csr-jjvt4
    resourceVersion: "354"
    uid: ba93c384-8318-4ae8-81c5-b0818032564f
  spec:
    extra:
      authentication.kubernetes.io/credential-id:
      - X509SHA256=78436190cc60678a5e5e4b01c3c8923d4bea6bdcfb5c5f22eb40f94522ab2275
    groups:
    - system:nodes
    - system:authenticated
    request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlIN01JR2lBZ0VBTUVBeEZUQVRCZ05WQkFvVERITjVjM1JsYlRwdWIyUmxjekVuTUNVR0ExVUVBeE1lYzNsegpkR1Z0T201dlpHVTZiV0ZwYmkxamIyNTBjbTlzTFhCc1lXNWxNRmt3RXdZSEtvWkl6ajBDQVFZSUtvWkl6ajBECkFRY0RRZ0FFOUFFbnl0a1E2TkpVL0FMQ296UStML3hKN2M2NnJQOGhKbGdLUk5mMGw5RlpZOGU0ZlFmVmJvSVoKR29KT085Myt1dzMzMlM4K0xJZW9WM216dVBTSmlxQUFNQW9HQ0NxR1NNNDlCQU1DQTBnQU1FVUNJUUN4ajRSMApqYmxDcEJNU2tnVkp2emxuVjBENkNSSDZ4b1ozd1BOQUl6aFRCd0lnT1JpUW5KUkUrR0RMSm5QSzFVUnQ1cWlEClU4Ky9tOFpzVWlrVnpsV2pVb2M9Ci0tLS0tRU5EIENFUlRJRklDQVRFIFJFUVVFU1QtLS0tLQo=
    signerName: kubernetes.io/kube-apiserver-client-kubelet
    usages:
    - digital signature
    - client auth
    username: system:node:main-control-plane
  status:
    certificate: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNhekNDQVZPZ0F3SUJBZ0lSQUp4bFBGdEVDMmpFOVhzaEpOaDdBSlV3RFFZSktvWklodmNOQVFFTEJRQXcKRlRFVE1CRUdBMVVFQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TmpBNE1EY3hNVEUwTWpoYUZ3MHlOekE0TURjeApNVEUwTWpoYU1FQXhGVEFUQmdOVkJBb1RESE41YzNSbGJUcHViMlJsY3pFbk1DVUdBMVVFQXhNZWMzbHpkR1Z0Ck9tNXZaR1U2YldGcGJpMWpiMjUwY205c0xYQnNZVzVsTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0QKUWdBRTlBRW55dGtRNk5KVS9BTENvelErTC94SjdjNjZyUDhoSmxnS1JOZjBsOUZaWThlNGZRZlZib0laR29KTwpPOTMrdXczMzJTOCtMSWVvVjNtenVQU0ppcU5XTUZRd0RnWURWUjBQQVFIL0JBUURBZ2VBTUJNR0ExVWRKUVFNCk1Bb0dDQ3NHQVFVRkJ3TUNNQXdHQTFVZEV3RUIvd1FDTUFBd0h3WURWUjBqQkJnd0ZvQVVMbmRCdmh0S203bFgKdkw3Z3ZSSS9GTFhCUTFvd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFFTmVpN05XNnZrNEJkdjlTaC9qT2srKwpJYnc4T0U4MThnVTBESDQvZHpUSlQzN1RDSHA3bGJHaWxSbWF5NHlxeERNR1AzL0NURjF5L2hrblZzTDF0ZlBWCmp3Vis2aUxoakl5OHNIZm9OaEN1cXJndzBtSXFFTmpobHFuM2tZMDRhL3lsWFE2WXVFR1RTTTBUMDBZWllHdk4KWEdBTlY2YmtTdHY4bHpjL0xZRGgzeWNIU2VWY3pML3VROUMydEVaYlV1emhUaHlTamFla2dkcFVWRm9MVHl3cApiZWdrY01qSlYxM3YyYWRmTVo1UTdYNWc4N1RZZ0QrcXpOUExabzdkSW81L1JIUkJRQms3WmxIekhMRHdqUHp3Clh0bmtUaWNqM0swZ1RxeEE2cG1YSFkvUG9IbSt5VGNaV3d4V3N4bmRpdzhMWnh5djBLQ0c0QkVBUVVRZGFQbz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    conditions:
    - lastTransitionTime: "2026-08-07T11:19:28Z"
      lastUpdateTime: "2026-08-07T11:19:28Z"
      message: Auto approving self kubelet client certificate after SubjectAccessReview.
      reason: AutoApproved
      status: "True"
      type: Approved
kind: List
metadata:
  resourceVersion: ""
