apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod2
  labels: 
    app: nginx2
spec:
  containers:
    - name: nginx2
      image: nginx:stable
      ports:
        - hostPort: 80
          containerPort: 80
